# Generated by Django 3.0.6 on 2020-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridges',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_of_repairs', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('total', models.IntegerField()),
            ],
            options={
                'ordering': ['-date_of_repairs'],
            },
        ),
    ]
