# Generated by Django 3.0.6 on 2020-05-18 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartridgelist', '0002_auto_20200518_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='date_of_repairs',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85a8591f-83de-4b33-a295-b8e57209ae50'), primary_key=True, serialize=False),
        ),
    ]
