# Generated by Django 3.0.6 on 2020-05-18 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartridgelist', '0003_auto_20200518_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridges',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartridges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d57ea424-e090-4159-8f91-c17e0e7193d7'), primary_key=True, serialize=False),
        ),
    ]
