# Generated by Django 3.0.6 on 2020-05-18 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartridgelist', '0004_auto_20200518_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e618b1d8-d1e8-4f63-a02f-4f3ad1b33c88'), primary_key=True, serialize=False),
        ),
    ]
