# Generated by Django 3.0.6 on 2020-05-18 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cartridgelist', '0005_auto_20200518_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d817bc10-6aa8-45a2-9ba1-ca4543f68b32'), primary_key=True, serialize=False),
        ),
    ]
